Added continue option in case of checksum mismatch. Fixed documentation.

diff --git a/install b/install
--- a/install
+++ b/install
@@ -16,7 +16,7 @@
 #
 
 srcdir='/usr/src/usr.sbin/httpd'
-patchdir="$(pwd)/$(dirname $0)"
+chksum='20eca3723840edaf89a483d32130f0dfd0714ba7a1c213e5f20b6fc3f37e5073'
 
 restore()
 {
@@ -27,20 +27,29 @@ restore()
 }
 
 if [[ $(id -u) != 0 ]]; then
-	echo 'need root privileges'
+	echo 'Need root privileges.'
 	exit 1
 fi
 if [[ ! -d ${srcdir} ]]; then
-	echo 'missing source tree'
+	echo 'Missing source tree.'
 	exit 1
 fi
 
 chksum0=$(find ${srcdir} \( -name '*.[chy578]' -o -name 'Makefile' \) \
 	-type f -maxdepth 1 -exec sha256 {} \; | sort -k 2 | sha256)
-chksum1='20eca3723840edaf89a483d32130f0dfd0714ba7a1c213e5f20b6fc3f37e5073'
-if [[ ${chksum0} != ${chksum1} ]]; then
-	echo 'Sources and patches do not match. Make sure both are up-to-date.'
-	exit 1
+if [[ ${chksum0} != ${chksum} ]]; then
+	echo 'Sources and patches do not match. Make sure ...'
+	echo '  ... the -current branch is in use.'
+	echo '  ... both are up-to-date.'
+	while :
+	do
+		echo -n 'Continue anyway (Not recommended!)? [y/N] '
+		read yn
+		case ${yn} in
+			y)	break;;
+			*)	echo 'Exiting.'; exit 1;;
+		esac
+	done
 fi
 
 echo -n 'Backing up original sources ... '
@@ -58,7 +67,7 @@ else
 fi
 
 echo 'Applying patch files ...'
-for f in $(find ${patchdir} -type f -name '*.patch' | sort); do
+for f in $(find $(pwd)/$(dirname $0) -type f -name '*.patch' | sort); do
 	echo "... $(basename ${f} .patch) ..."
 	cat ${f} | (cd /usr/src && patch -p0)
 	if [[ $? -ne 0 ]]; then
